### ISSUE TITLE
ui: error on browser console - TypeError undefined is not an object (evaluating 'Object.keys(this.content)')

### ISSUE THREAD

**Issue by italovalcy** [amlight/SDNTrace#72]
Hi,

During the usage of Kytos with sdntrace UI enabled I got this error on the console:

![Screenshot 2024-05-20 at 17 26 00](https://github.com/kytos-ng/sdntrace/assets/168159/ab3d36d7-b64f-4fd4-aa9b-eac9011d48a8)

The detailed output was a log message I added to further investigate with the following change to the code:

```
$ grep -n -C 3 Italo ./node_modules/vue/dist/vue.esm.js
3783-    /* istanbul ignore else */
3784-    if (inBrowser && typeof console !== 'undefined') {
3785-        console.error(err);
3786:        console.log("Italo - Error in ".concat(info, ": \"").concat(err.toString(), "\""), vm);
3787-    }
3788-    else {
3789-        throw err;
```

**Comment by italovalcy** [comment]
This issue will be fixed by PR https://github.com/kytos-ng/sdntrace_cp/pull/116/files#diff-15d1fcf1f7cbb6ab5093b007bb346e5d0c3dc21cc852b0aeeefacf719d4ab5acR45

**Comment by viniarck** [comment]
This landed on https://github.com/kytos-ng/sdntrace_cp/pull/116/files#diff-15d1fcf1f7cbb6ab5093b007bb346e5d0c3dc21cc852b0aeeefacf719d4ab5acR45
