### ISSUE TITLE
UI: add support to set `tp` (transport protocol) , `tp_src` and `tp_dst` on k-toolbar

### ISSUE THREAD

**Issue by viniarck** [amlight/SDNTrace#90]
This is to support [`tp` (transport protocol)](https://github.com/kytos-ng/sdntrace/blob/master/openapi.yml#L171), to set `tp_src` and `tp_dst` on k-toolbar that has been introduced on https://github.com/kytos-ng/sdntrace/pull/80. 

It turns out when the students contributed with the UI back then https://github.com/kytos-ng/sdntrace/pull/68/files we still didn't have support for setting tcp or udp ports, so that has been left behind.  The backend has been e2e tests and the functionality is working, it's just a matter of exposing `tp` attrs on the the `k-toolbar` now. 

@Ktmi can you help out with this one? cc'ing @Alopalao for his information too.

**Comment by Ktmi** [comment]
I'll be working on this.
