### ISSUE TITLE
Can't Set DPID in UI

### ISSUE THREAD

**Issue by Ktmi** [amlight/SDNTrace#91]
Can't seem to set the DPID for the trace in the web UI. I'm using firefox 128.0.3. Same thing happens with `sdntrace_cp`. Issue for sdntrace_cp at kytos-ng/sdntrace_cp#121

**Comment by viniarck** [comment]
@Ktmi, on firefox 128.0.2 on Linux it's working for me, and on google-chrome too:

![20240805_113628](https://github.com/user-attachments/assets/c7d0f928-6dde-40cf-8e89-d41c3e6aafbd)

What errors are you getting in the console? Check out if you've got the latest `ui` and if it has been built recently.

**Comment by viniarck** [comment]
On firefox 128.0.2 it's working for me, which errors are you getting? Same comment as https://github.com/kytos-ng/sdntrace_cp/issues/121#issuecomment-2269244387

![20240805_114140](https://github.com/user-attachments/assets/308874ae-1e61-45ec-8123-601730e8781a)

**Comment by Ktmi** [comment]
I'm thinking this is because I use named switches?
![image](https://github.com/user-attachments/assets/3a000fb9-746b-4240-97fc-56586901a6c3)
I'm not seeing any errors in the log regarding requests.
![image](https://github.com/user-attachments/assets/b2be5661-0784-4e3e-8487-b742f11cb3e6)

**Comment by viniarck** [comment]
> I'm thinking this is because I use named switches? 

I tried here with `node_name` on sw1 and when selecting it, it correctly derived the dpid value too. 

![20240806_123948](https://github.com/user-attachments/assets/27b222a0-1de0-4784-ac06-f8c76dd00af5)

![20240806_124000](https://github.com/user-attachments/assets/9a4dc721-4e42-413e-b2ed-65732e5a8044)


When you select the dpid value does it stay empty, David? If the UI is still being able to make the request check out which payload it has sent too to see if it's correct.

**Comment by Ktmi** [comment]
Yes, the DPID remains empty, and I can not select the port number. Attempting to start the trace does nothing. Actually, attempting to do other actions with the UI also appears to not be working?

**Comment by Ktmi** [comment]
Checking with what is definitely the latest UI version, I am still not able to set the DPID, or run other UI elements correctly.

**Comment by Ktmi** [comment]
Switching to chromium, this works correctly on that, but on Firefox, it doesn't work.
